### ISSUE TITLE
Missing error handler on `socket`. I install this with  npm install q

### ISSUE THREAD

**Issue by AnD010** [krasimir/react-webpack-starter#7] opened 2016-02-25 18:41 UTC
Hi!
I´m rookie with nodejs and with promises, I installed Q.js with npm :  
 npm install q
I´m try yo make a promise when I made a query to postgres, this is my code...

   ```
socket.on('Operation', function (data) {
....... 
getElementInPostgres(makeQuery)
    .then(function (name) {
          console.log("promiseeee then");
          .......blablabla
  })
    .fail(function (err) {
      console.log("promiseeee error");

    });
.............
function getElementInPostgres(makeQuery){
  console.log("entro getElementInPostgres");
  var deferred = Q.defer();
  client.query(
                  makeQuery,
                  function(err, result) {
                    if (err) {
                       console.log("NO getElementInPostgres");
                      console.log(err);
                      deferred.reject(err);
                    } else {
                       console.log("ok getElementInPostgres");
                     console.log(result);
                     deferred.resolve(result);
                    }
                    return deferred.promise;
                });
}
```
But my code crash 
Missing error handler on `socket`.
TypeError: Cannot call method 'then' of undefined.....

I was looking at examples and do not see anything different in my code ...

Thanks !

**Comment by krasimir** [comment] 2016-02-26 05:13
Hi @AnD010,

I'm afraid that your problem is not related to [react-webpack-started](https://github.com/krasimir/react-webpack-starter). So, the place for this issue is not here. I don't have experience with Q.js but it seems that the problem is not there. May be something in your postgres process or the postgres node driver. 

I'm closing this one and I'll suggest asking in the appropriate repo or StackOverflow.

**Closed by krasimir** 2016-02-26 05:13 UTC

**Comment by AnD010** [comment] 2016-02-26 07:42
Sorry @krasimir ,
I thought what I made the question in the correct thread.
I´m sure the problem is because Q.js when I make the promisse.
Thanks :) and sorry for my mistake

**Comment by krasimir** [comment] 2016-02-26 09:05
No worries :)
