### ISSUE TITLE
Some errors on npm test

### ISSUE THREAD

**Issue by Sensiblemnd** [krasimir/react-webpack-starter#6] opened 2016-01-15 14:16 UTC
node version 0.12.1

npm test

> react-webpack-starter@0.1.2 test /Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master
> karma start

15 01 2016 09:13:13.223:INFO [karma]: Karma v0.13.10 server started at http://localhost:9876/
15 01 2016 09:13:13.228:INFO [launcher]: Starting browser PhantomJS
15 01 2016 09:13:14.475:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket /#yi9ygzVp7DeIA3VTAAAA with id 94632065
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR: 'Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.'

Start:
  Given an instance of the Component
    when we render the component
      ✔ should render a paragraph

Finished in 0.014 secs / 0.001 secs

SUMMARY:
✔ 1 test completed
Missing error handler on `socket`.
TypeError: undefined is not a function
    at disconnectBrowsers (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:311:13)
    at null.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:291:7)
    at emit (events.js:129:20)
    at emitRunCompleteIfAllBrowsersDone (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:256:12)
    at null.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:278:9)
    at emit (events.js:129:20)
    at onComplete (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/browser.js:142:13)
    at Socket.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/events.js:13:22)
    at Socket.emit (events.js:129:20)
    at Socket.onevent (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/socket.io/lib/client.js:175:18)
    at Socket.emit (events.js:107:17)
15 01 2016 09:13:24.575:WARN [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

Finished in 10.028 secs / 0.001 secs

15 01 2016 09:13:24.577:ERROR [karma]: [TypeError: undefined is not a function]
TypeError: undefined is not a function
    at disconnectBrowsers (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:311:13)
    at null.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:291:7)
    at emit (events.js:129:20)
    at emitRunCompleteIfAllBrowsersDone (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:256:12)
    at null.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:278:9)
    at emit (events.js:129:20)
    at null._onTimeout (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/browser.js:50:15)
    at Timer.listOnTimeout (timers.js:110:15)
/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:311
    sockets.forEach(function (socket) {
            ^
TypeError: undefined is not a function
    at disconnectBrowsers (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:311:13)
    at process.<anonymous> (/Users/34903/Desktop/Projects/reactTests/react-webpack-starter-master/node_modules/karma/lib/server.js:352:5)
    at process.emit (events.js:107:17)
    at process._fatalException (node.js:236:26)
npm ERR! Test failed.  See above for more details.

**Comment by krasimir** [comment] 2016-01-15 14:31
Thanks for the report @Sensiblemnd 
I'll try to reproduce the problem locally.

**Comment by krasimir** [comment] 2016-01-20 03:29
@Sensiblemnd the problem should be fixed now. I released a new `0.1.3` version. The issue is mentioned here https://github.com/karma-runner/karma/issues/1751 and it is fixed in `0.13.19` version of `karma`. So I simply updated to this version. Let me know if it works on your machine.

**Comment by krasimir** [comment] 2016-01-23 07:18
@Sensiblemnd I believe that the issue is fixed. I'm closing this. Let me know if it's not working as expected on your machine and I'll reopen it.

**Closed by krasimir** 2016-01-23 07:18 UTC
Labels: bug, feedback required
